### ISSUE TITLE
Drive access does not work when accessing sharepoint drives.

### ISSUE THREAD

**Issue by Cellebyte** [janscas/py-o365#10]
## How to reproduce

```python
resource = "sites/{hostname}:/{type}/{page}:".format(hostname=company_hostname, type='sites', page="page/subpage")
protocol = MSGraphProtocol()
account = Account(credentials=credentials, protocol=protocol)
storage = account.storage(resource=resource)
drives = storage.get_drives()

for drive in drives:
    drive.get_items() # not working because the _base_url is wrong

```

## Temporary Fix

```python
drive._base_url = drive._base_url.replace(resource, "")
```

## Solution

Drive items cannot be accessed under the resource of a sharepoint.
The drives should be always initialized with the root base_url /drives/{drive_id}.

Feel free to close it ^^

**Comment by alejcas** [comment]
I’ll see this next week, thanks!

**Comment by Cellebyte** [comment]
@janscas i have also a fix for not being able to create folders via create_child_folder attribute.

**Comment by alejcas** [comment]
I've just merged your pull request.

I'll have to further check this issue with the sharepoint resource.

**Comment by Cellebyte** [comment]
> I'll have to further check this issue with the sharepoint resource.

The drive-id you get from the sharepoint is not available under `sharepoint:page/subpage/drives/drive-id`, it is only direct available under `/drives/drive-id` so you must change the initialization of the base_url from being `resource/drives` to only `/drives` if you want to access the drives from the specified sharepoint resource.

**Comment by alejcas** [comment]
ok, I'll run some tests and report back. thanks

**Comment by alejcas** [comment]
First of all the sharepoint api is not ready yet. In the near future you will have a account.sharepoint() or something like this.

But, you can still use the storage class to retrieve files and folders from a sharepoint site document library.

Just use the main resource such as:

```python
storage = account.storage(resource='sites/my-site-id')  # set my-site-id to the real site id.

drive = storage.get_default_drive(request_drive=True)

print(drive)  # this works and will print the name of the default drive
```

From here you can work with the `drive`object to further work with files and folders on the document library of your sharepoint site.

You can also access the sites drives using a different site resource (like using relative paths, etc)
Check the graph docs.

**Comment by alejcas** [comment]
Note that if you don't know the site id you can also access a Document Library of a Sharepoint site by the site path such as:

```python
storage = account.storage(resource='sites/my-hostname.sharepoint.com:/sites/my-site:')  
# you just need to set your host name and the site name in the path
#   (or the path to the site under my-hostname.sharepoint.com).

drive = storage.get_default_drive(request_drive=True)

print(drive)  # this works and will print the name of the default drive
```

I'll close this issue.
