### ISSUE TITLE
body_type (html and text)

### ISSUE THREAD

**Issue by jessepink** [janscas/py-o365#12]
This is more of a feature request than an issue, but it would be nice to be able send emails in both html and text formats (i.e. multiple body_types, for maximum compatibility to people that may not have an HTML compatible client, or prefers to read email as text only).  I know how to do this with the python smtplib + email libraries, but to keep things simplified, would be beneficial to be able to do this natively with "only" pyo365.

If this is already possible, I haven't figured out how to make it work.

**Comment by alejcas** [comment]
This is already implemented. Simply set `body_type ` on a `Message` instance to 'text' (defaults to 'HTML').

**Comment by jessepink** [comment]
Then there needs to be some clarification on how to make this work, because I cannot figure it out:

`m = account.new_message()`
`m.to.add('emailaddress@gmail.com')`
`m.subject = 'Testing!'`
`m.body_type = 'HTML'`
`m.body = '<html><head></head><body><h1>This is the html portion</h1></body></html>'`
`print(f'm.body = {m.body}')`
`m.body_type = 'text'`
`m.body = 'This is a text portion of the email.'`
`print(f'm.body redux = {m.body}')`

results in:
`m.body = <html><head></head><body><h1>This is the html portion</h1></body></html>`
`m.body redux = <html><head></head><body>This is a text portion of the email.<h1>This is the html portion</h1></body></html>`

If I switch up which one is done first (i.e. putting the text assignment before the html assignment, I get:
`Traceback (most recent call last):`
`  File "D:/O365test/O365test.py", line 40, in <module>
    m.body = '<html><head></head><body><h1>This is the html portion</h1></body></html>'`
`  File "C:\Users\xxx\.virtualenvs\O365test-3Wjh4Anz\lib\site-packages\pyo365\message.py", line 298, in body`
    soup.body.insert(0, value)
`AttributeError: 'NoneType' object has no attribute 'insert'`
`m.body = This is a text portion of the email.`

**Comment by alejcas** [comment]
The print on `message.body` will always print in plain text no matter what.

This works:

```python
message = account.new_message()

message.subject = 'test'
message.body_type = 'text'
message.body = 'This is a <strong>test</strong>'
message.to.add('to_mail_adress@example.com')

message.send()
```

'to_mail_adress@example.com' will receive a message with body: 'This is a &lt;strong>test&lt;/strong>' (the tags appear as text).

Hope this answers your question.

**Comment by jessepink** [comment]
I don't think I'm explaining the need appropriately... regardless of how python's print statement works.

What I want is my email to have _two_ body types.  One for HTML readers, and one text only readers.  Currently there is no way to include both body types in a single email, that I can figure out.   I have done this using straight smtplib and email libraries, but would prefer to use pyo365 because it handles the authentication and other useful things in a single package.

**Comment by alejcas** [comment]
Ok, first of all a message can only have one body type. But, you can get from a message body three things:

1. The body in plain text with the property `body` regardless of the body type.
2. The body text (just the text) with the method `get_body_text`. If the body type is not 'HTML' it just returns the body.
3. The body soup object with `get_body_soup`. A beautifullsoup4 object that you can play to navigate through the body tags. Returns `None` if the body type is not 'HTML'. This is the most powerfull option.

**Comment by alejcas** [comment]
> I have done this using straight smtplib

Maybe you are talking about using MIMEMultipart. This is not something currently supported by the api. I can't see this working the way you want. But at the end, you can send html and play with the soup object to extract whatever parts of a message you want.

**Comment by jessepink** [comment]
Yes, the way I've done it in the past is using using `from email.mime.multipart import MIMEMultipart`

**Comment by jessepink** [comment]
This maybe should be another "issue," but the way that you currently insert new data to a forward or reply (through beautifulsoup) will actually sanitize the "new" html, which at least in my case is not what I want it to do.

It's a fairly easy workaround though, which is basically just to encapsulate the new part of my message, i.e. `<h1>This is my new reply</h1>` into it's own bs object:


        foward_text = bs('<h1>This is my new forward</h1>', 'html.parser')
        forward_message.body = forward_text

I'm not sure if this should be an option or not, but it may at least be beneficial to put it in the documentation.

**Comment by alejcas** [comment]
Yep! that was an unintended effect. I have commited bd38c7d4a8ad1f027fe303abc9f8506b9166cec8 that solves this.



Thanks!
