### ISSUE TITLE
Question about get_authorization_url

### ISSUE THREAD

**Issue by jwhugheskp** [janscas/py-o365#13]
Hi Alejandro,

I'm walking through the README.md working out the order of the code needed to pull from a mailbox and I ran into this error

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/lib/python3.7/site-packages/pyo365/connection.py", line 301, in get_authorization_url
    raise ValueError('Must provide at least one scope')
ValueError: Must provide at least one scope

This is the order of the steps I did.

Python 3.7.0 (default, Jun 28 2018, 07:39:16) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> url = account.connection.get_authorization_url()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'account' is not defined
>>> from pyo365 import Account
>>> credentials = ('client_id', 'client_secret')
>>> account = Account(credentials)
>>> url = account.connection.get_authorization_url()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/lib/python3.7/site-packages/pyo365/connection.py", line 301, in get_authorization_url
    raise ValueError('Must provide at least one scope')
ValueError: Must provide at least one scope
>>> scopes = ['https://graph.microsoft.com/Mail.ReadWrite', 'https://graph.microsoft.com/Mail.Send']
>>> from pyo365 import Connection
>>> con = Connection(credentials, scopes=scopes)
>>> url = account.connection.get_authorization_url()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/lib/python3.7/site-packages/pyo365/connection.py", line 301, in get_authorization_url
    raise ValueError('Must provide at least one scope')
ValueError: Must provide at least one scope

Even though I set the scope I must have missed a step I must have set it the wrong way.  What is needed to get the url line to work?

TIA,
Joe

**Comment by alejcas** [comment]
First of all follow the steps for registering an application on the Microsoft Application Registration Portal. Assign the permissions required, etc. Those are the scopes you need to pass to the Connection.

I'll guide you here:

1. First you must get the authentication token. You can do this manually (as you where doing on your example) or with some helpers. To use the helpers (recommended) just check this [using-pyo365-to-authenticate](https://github.com/janscas/pyo365#using-pyo365-to-authenticate).

The scopes you pass to `account.authenticate` are protocol agnostic. To see which ones you can pass check this: [scopes](https://github.com/janscas/pyo365/blob/master/pyo365/connection.py#L30).
You can pass some or all the ones you assign on the first step, but not more.

2. Then to use pyo365, once you have the auth token, just use it like this:

```python
account = Account(('client_id', 'client_secret'))  # this will use the stored token retrieved in the previous step with the scopes you requested.
# sending an email for example:
msg = account.new_message()

msg.to.add('email@email.com')
msg.subject = 'hi there!'
msg.send()
```
Hope this helps.

**Comment by jwhugheskp** [comment]
Hi Alejandro,

This is the code I'm trying to get to work.  I have the client_id and client_secret from the app.

from pyo365 import Account, Connection, MSGraphProtocol
  
credentials = ('client_id', 'client_secret')
scopes = ['https://graph.microsoft.com/Mail.ReadWrite', 'https://graph.microsoft.com/Mail.Send']
con = Connection(credentials, scopes=scopes)
#url = account.connection.get_authorization_url()

protocol = MSGraphProtocol(api_version='beta')
account = Account(credentials)
m = account.new_message()
m.to.add('joseph.hughes@kp.org')
m.subject = 'Outlook Python Testing!'
m.body = "George Best quote: I've stopped drinking, but only while I'm asleep."
m.send()

This is the error I get when I run it

python send_mail.py
Traceback (most recent call last):
  File "send_mail.py", line 14, in <module>
    m.send()
  File "/anaconda3/lib/python3.7/site-packages/pyo365/message.py", line 454, in send
    response = self.con.post(url, data=data)
  File "/anaconda3/lib/python3.7/site-packages/pyo365/connection.py", line 481, in post
    return self.oauth_request(url, 'post', data=data, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/pyo365/connection.py", line 471, in oauth_request
    self.get_session()
  File "/anaconda3/lib/python3.7/site-packages/pyo365/connection.py", line 365, in get_session
    raise RuntimeError('No auth token found. Authentication Flow needed')
RuntimeError: No auth token found. Authentication Flow needed

Even with your samples, I don't see what I'm missing.

TIA,
Joe

**Comment by alejcas** [comment]
> scopes = ['https://graph.microsoft.com/Mail.ReadWrite', 'https://graph.microsoft.com/Mail.Send']
> con = Connection(credentials, scopes=scopes)

Scopes are only needed when generating the oauth token. Later on you don't need scopes any more because those are stored on the token file.

> con = Connection(credentials, scopes=scopes)

These connection is never used. You created con and never used it again.

> protocol = MSGraphProtocol(api_version='beta')

This protocol is never used in your example.

### **Please review the docs and the links I sent to you previously.**

**Comment by alejcas** [comment]
> RuntimeError: No auth token found. Authentication Flow needed

Have you read my answer??? It seems to me that you don't.

The error is saying to you that you need to run the authentication flow first.

**Comment by jwhugheskp** [comment]
Hi Alejandro,

I read your answer, but it still doesn't make sense to me.  This is the authentication flow.

Authentication Flow
To work with oauth you first need to register your application at Microsoft Application Registration Portal.

**Login at Microsoft Application Registration Portal
Create an app, note your app id (client_id)
Generate a new password (client_secret) under "Application Secrets" section
Under the "Platform" section, add a new Web platform and set "https://outlook.office365.com/owa/" as the redirect URL
Under "Microsoft Graph Permissions" section, add the delegated permissions you want (see scopes), as an example, to read and send emails use:
Mail.ReadWrite
Mail.Send
User.Read
Then you need to login for the first time to get the access token by consenting the application to access the resources it needs.

First get the authorization url.

url = account.connection.get_authorization_url()**

I did all the above down to this

Then you need to login for the first time to get the access token by consenting the application to access the resources it needs.

First get the authorization url.

url = account.connection.get_authorization_url()

Is the login via the url line or via the MS Application Registration Portal?  On the application page I have everything configured for an app using what is listed as the scope because that is what I'm trying to do.  I understand I need a token, but how do I get one?

TIA,
Joe

**Comment by alejcas** [comment]
1. First read [using-pyo365-to-authenticate](https://github.com/janscas/pyo365#using-pyo365-to-authenticate).

use option one, so run (change client id, secret and scopes as you need):
```python
account = Account(credentials=('client_id', 'client_secret'))
result = account.authenticate(scopes=['basic', 'message_all'])  # request a token for this scopes
```

**If at the end result is True, you will have a file on your project root folder called 'o365_token.txt'.**
If not, ____go back because you did something wrong____.

This step is only needed once. All the other calls to the api only need the token.

2. Once you have the token, use the api (Don't use scopes here):

```python
account = Account(('client_id', 'client_secret'))  # this will use the stored token retrieved in the previous step with the scopes you requested.
# sending an email for example:
msg = account.new_message()

msg.to.add('email@email.com')
msg.subject = 'hi there!'
msg.send()
```

**Comment by jwhugheskp** [comment]
Hi Alejandro,

It finally fell into place in my mind and I was able to get the token.  Thanks for your assistance.

Regards,
Joe

**Comment by alejcas** [comment]
> It finally fell into place in my mind and I was able to get the token.

Great!
