### ISSUE TITLE
Global address book filter with multiple paramaters

### ISSUE THREAD

**Issue by Xalaxis** [janscas/py-o365#18]
I seem to be having problems using a query with multiple parameters.  The code below works if the "q.endswith" line is removed.

```
global_address_list = account.address_book(address_book='gal')
q = global_address_list.new_query('display_name')
q.startswith("John")
q.endswith("Smith")
print(global_address_list.get_contacts(query=q, limit=5))
```

Client Error: 400 Client Error: Bad Request for url: https://graph.microsoft.com/v1.0/users?%24top=5&%24filter=startswith%28displayName%2C+%27John%27%29+and+endswith%28displayName%2C+%27Smith%27%29

**Comment by alejcas** [comment]
Hi, this has nothing to do with the pyo365 library.

The filters (and number of filters) allowed by Microsoft on the graph (and office 365 Rest ) api are very obscure and varies depending on the resource retrieved.

Currently the OData keyword 'endswith' is not supported by Microsoft Graph (who knows in the future).
For example the 'contains' keyword is sometimes supported. But not in the 'users' endpoint that the global address book uses.

Try to use the [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) to see if the filters you apply work or not.

**Comment by Xalaxis** [comment]
Okay, thank you.
