### ISSUE TITLE
Number of Attachments Count

### ISSUE THREAD

**Issue by jwhugheskp** [janscas/py-o365#19]
Hi Alejandro,

I dumped the message dictionary and found this for the one message with an attachment.

'_Message__attachments': Number of Attachments: unknown

Besides counting each attachment as I loop through the attachments to give me a final count, is there another place the attachment count would be?

TIA,
Joe

**Comment by alejcas** [comment]
`len(message.attachments)`

But to work you will have to download the attachments first

**Comment by jwhugheskp** [comment]
Hi Alejandro,

The code

        if message.has_attachments:
            print("Attachments:", len(message.attachments))

The result

Attachments: 0

I know two of my emails have 1 attachment and the code comes back with 0.  Ideas?

TIA,
Joe

**Comment by alejcas** [comment]
As we discuss in #17, you have to dowload the attachments first.

**Comment by jwhugheskp** [comment]
Hi Alejandro,

I read it, but now I understand.  Before you can do anything you have to download the attachments into memory.

Thanks,
Joe

**Comment by alejcas** [comment]
yep, the message itself only knows if it has attachments or not. For further info, we have to download the attachments.

You're welcome
