### ISSUE TITLE
Refresh Token

### ISSUE THREAD

**Issue by jwhugheskp** [janscas/py-o365#20]
Hi Alejandro,

I'm now stuck trying to refresh the token.  I'm trying to write the code so the user authenticates once and then the token is refreshed every hour.  I've read this section

If your application needs to work for more than 90 days without user interaction and without interacting with the API, then you must implement a periodic call to Connection.refresh_token before the 90 days have passed.

I haven't been able to figure out what is needed to refresh the token.  My code looks like this

```
def main():
    token_file = Path(TOKEN_PATH)

    if not token_file.is_file():
        authentication()

    while True:
        try:
            print_email()
        except TokenExpiredError:
            create_time = os.stat(TOKEN_PATH).st_ctime
            print("Create Time", create_time)

            Connection.refresh_token()
```

The code checks to see if the token file exists.  If it doesn't exist, then create it.  A first login.  Then loop forever looking for email.  When the token expires check the create time and then try to do a refresh of the token.

I must be missing something when it comes refreshing the token.

TIA,
Joe

**Comment by alejcas** [comment]
The token is refreshed for you automatically (if needed) every time you make a request to the microsoft services. 

But this only aplies if the last token refresh was done less than 90 days in the past.

Usually you will use the api before that.

**Comment by jwhugheskp** [comment]
Hi Alejandro,

What do you mean it is automatically refreshed?  My current token expires after 1 hour.  How could I get the new token every time the script is run?

TIA,
Joe

**Comment by alejcas** [comment]
First you have to give offline acces permission to your app. Then request this scope when authenticating. 

Then, with your token comes a refresh token that is used to refresh your token every time it expires.

Just check the token file and you will see it there.

**Comment by jwhugheskp** [comment]
Hi Alejandro,

Okay that makes sense.  I changed my global scope variable to this

SCOPES = ['https://graph.microsoft.com/Mail.ReadWrite', 'https://graph.microsoft.com/Mail.Send', 'https://graph.microsoft.com/Mail.offline_access']

and now I'm getting a scope error.  I also tried this

SCOPES = ['https://graph.microsoft.com/Mail.ReadWrite', 'https://graph.microsoft.com/Mail.Send', 'https://graph.microsoft.com/OpenID.offline_access']

and I still get an error.  I see offline_access in connection.py.  Should I use basic, message_send, and message_all instead of calling the graph ones?

TIA,
Joe

**Comment by alejcas** [comment]
I recommend you to not use scopes directly.

As I told you on #13, review the [scopes](https://github.com/janscas/pyo365/blob/master/pyo365/connection.py#L30) you can pass to `account.authenticate` .

for example:

`account.authenticate(scopes=['basic'])`

This 'basic' keyword will ask for offine_access and User.Read, as stated [here](https://github.com/janscas/pyo365/blob/master/pyo365/connection.py#L30).

Those scopes are protocol agnostic, so you don't have to know the scope full path.

**Comment by jwhugheskp** [comment]
Hi Alejandro,

Okay this is the code.

```
#!/usr/bin/python
#
#########################################################################
# Program    : get_spam_email.py
# Purpose    :
# Programmer : Joe Hughes
#
#########################################################################

#########################################################################
# Froms
#########################################################################
#
from pathlib import Path
from pyo365 import Account, Connection, MSGraphProtocol

#########################################################################
# Imports
#########################################################################
#
import datetime
import os

#########################################################################
# Constants
#########################################################################
#

#########################################################################
# Globals
#########################################################################
#
CREDENTIALS = ('client_id', 'client_secret')
SAVE_PATH = "/root/jwh"
SCOPES = ['basic', 'mailbox']
TOKEN_PATH = "/root/o365_token.txt"

#########################################################################
# Functions
#########################################################################
#
def authentication():
    account = Account(credentials = CREDENTIALS)
    result = account.authenticate(scopes = SCOPES)
    print(result)

def print_email():
    account = Account(credentials = CREDENTIALS)
    mailbox = account.mailbox()
    inbox = mailbox.inbox_folder()

    for message in inbox.get_messages(limit=50):
        print(132*"-")
        print("---------- Message Header Begin ----------")
        print("Object Id:", message.object_id)
        print("Message Body Type:", message.body_type)
        print("Subject:", message.subject)
        print("From:", message.sender)

        for recipient in message.to:
            print("To:", recipient)

        if message.cc:
            for recipient in message.cc:
                print("CC:", recipient)
        else:
            print("CC", message.cc)

        if message.bcc:
            for recipient in message.bcc:
                print("BCC:", recipient)
        else:
            print("BCC", message.bcc)

        if message.reply_to:
            print(message.reply_to)

        print("Importance:", message.importance.name)

        if message.has_attachments:
            #
            # Create the attachment directory
            #
            save_directory = SAVE_PATH + "/" + str(message.object_id)
            os.makedirs(save_directory)

            #
            # Download the message attachments into memory prior to any data pulls from the attachment.
            # Need a call to 'attachment.save' to save them on disk.
            #
            message.attachments.download_attachments()
            print("Attachments:", len(message.attachments))

            for attachment in message.attachments:
                print(attachment)
                #
                # Save the attachment locally to disk.
                # :param location: path string to where the file is to be saved.
                # :param custom_name: a custom name to be saved as
                #
                attachment.save(location=save_directory)

        print("Message Sent:    ", message.sent)
        print("Message Created: ", message.created)
        print("Message Recieved:", message.received)
        print("Message Modified:", message.modified)
        print("Message Read:", message.is_read)
        print("----------- Message Header End -----------")
        print("----------- Message Body Begin -----------")
        print(message.get_body_text())
        print("------------ Message Body End ------------")
        print(132*"-")

def main():
    token_file = Path(TOKEN_PATH)

    if not token_file.is_file():
        authentication()

    print_email()

#########################################################################
# Main Program
#########################################################################
#

if __name__ == '__main__':
    main()
```

The code does everything I want at this moment except generate a refresh token.  Once I get that working I need to work on a filter to only read new mail.  Any ideas on what I'm missing?

TIA,
Joe

**Comment by alejcas** [comment]
You can use pathlib since u're importing it.

Instead:
> save_directory = SAVE_PATH + "/" + str(message.object_id) 
> os.makedirs(save_directory)

do:
```python
save_directory = Path(SAVE_PATH) / Path(message.object_id)
save_directory.mkdir(exist_ok=True)
```


What you are doing is ok. If authentication results in True, then the file at "/root/o365_token.txt" will have a key called "refresh_token" with the refresh token.

If you have the refresh token then the token is refreshed automatically.

To check that this happens simply set the logging to debug:

```python
import logging
logging.basicConfig(level=logging.DEBUG)
```

Then after some time have passed since the last request you should see (these messages are interlaced with some other that I don't copy here):
```
INFO:pyo365.connection:Oauth Token is expired, fetching a new token
DEBUG:requests_oauthlib.oauth2_session:Requesting url https://login.microsoftonline.com/common/oauth2/v2.0/token using method POST.
DEBUG:requests_oauthlib.oauth2_session:Request to refresh token completed with status 200.
```

**Comment by jwhugheskp** [comment]
Hi Alejandro,

Thanks.  It is working.  The next thing I need to figure out is how to only get new emails since the last read.

Regards,
Joe

**Comment by alejcas** [comment]
> The next thing I need to figure out is how to only get new emails since the last read.

Just use a query helper:

```python
inbox = mailbox.inbox_folder()

query = inbox.new_query('is_read').equals(False)
# you can use 'inbox.q' instead of 'inbox.new_query' as a shortcut

unread_messages = inbox.get_messages(limit=50, query=query)
```

**Comment by alejcas** [comment]
> token_file.is_file()

Instead of this you should check `token_file.exists()`
