### ISSUE TITLE
Unable to complete authentication

### ISSUE THREAD

**Issue by zimws** [janscas/py-o365#21]
Hi,

I tried to use the first example to send a message but it said No auth token found. Authentication Flow needed. So I follow the authentication flow section. I completed the registration and input my clientID and password. At 2i get the authorisation url, I tried url = account.connection.get_authorization_url(). I got the message that "Must provide at least one scope".  

I am not sure what this means so I tried the Using pyo365 to authenticate section. I ran result = oauth_authentication_flow('client_id', 'client_secret', ['scopes_required']) and I got a url. I visited the url to provide consent then the web direct me to the outlook mailbox page. I paste the url to Paste the authenticated url here but then my python freezed.

Could anyone help me and advise how I could fix this issue?

Many thanks,
Wen

**Comment by alejcas** [comment]
First you have to autheticate. Use:

```python
account = Account(credentials)
account.authenticate()
```

**Comment by zimws** [comment]
account.authenticate() returns an error and asks me to include the scope. Then I use account.authenticate(scopes=['basic', 'message_all']). It then says Visit the following url to give consent:
https://login.microsoftonline.com/blablablaxxxxxxx. I go to the url and I selected my outlook account. It then direct me to my outlook email page. I copied the url https://outlook.office365.com/owa/?code=Oblablablablablaxxxxxxxxxxx. Then my python is not responding anymore.

**Comment by alejcas** [comment]
First of all you have to configure the app on the microsoft aplication registration portal. There you must grant some permissions to your applications. Then with this library you have to authenticate will all or at least some of the permissions you grant to your application.

When using account.authenticate(), you must pass scope helpers like you did:
'basic' translates to 'offline_access' and 'User.Read'. And 'message.all' let you read and send emails.

You did all the steps correctly, I recommend you two things:
1. first check the return value of account.authenticate(). If it's True, then the process is done and ok.
2. then check that after you authenticate, a file called 'o365_token.txt' appears on your project root. You can inspect this file to see the scopes granted and other things. Do not change this file.

If after all you don't have the token file, then something went wrong and you have to try again. Maybe you requested some scopes that your app has not access to or something like this.

Let me know if it helps.

**Comment by zimws** [comment]
Unfortunately, after I follow the instruction "paste the authenticated url here", it stopped responding. So I believe the authentication is not completed. Is it correct to paste the url which shows my outlook email?

**Comment by alejcas** [comment]
Yes, that's exactly what you have to do. Can you please:

```python
import logging
logging.basicConfig(level=logging.DEBUG)
```

This way it will print all the library debug messages. Can you paste them here **(please don't paste your client secret or the complete auth url)**.

**Comment by zimws** [comment]
it says DEBUG:requests_oauthlib.oauth2_session:Generated new state

**Comment by alejcas** [comment]
only this? That's not possible.. do you login and give consent? 

This is what the log outputs for me:

Before pasting the authenticated url:
`DEBUG:requests_oauthlib.oauth2_session:Generated new state xxxxxxxxxxxxxxxx`

After pasting the authenticated url (I removed the secret data):

```
DEBUG:requests_oauthlib.oauth2_session:Encoding client_id "my-client-id" with client_secret as Basic auth credentials.
DEBUG:requests_oauthlib.oauth2_session:Requesting url https://login.microsoftonline.com/common/oauth2/v2.0/token using method POST.
DEBUG:requests_oauthlib.oauth2_session:Supplying headers {'Accept': 'application/json', 'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8'} and data {'grant_type': 'authorization_code', 'code': 'my-code', 'client_id': 'my-client-id', 'redirect_uri': 'https://outlook.office365.com/owa/', 'client_secret': 'my-client-secret'}
DEBUG:requests_oauthlib.oauth2_session:Passing through key word arguments {'json': None, 'timeout': None, 'auth': <requests.auth.HTTPBasicAuth object at 0x0280C930>, 'verify': True, 'proxies': None}.
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): login.microsoftonline.com:443
DEBUG:urllib3.connectionpool:https://login.microsoftonline.com:443 "POST /common/oauth2/v2.0/token HTTP/1.1" 200 3997
DEBUG:requests_oauthlib.oauth2_session:Prepared fetch token request body grant_type=authorization_code&code=my-code&client_id=my-client-id&redirect_uri=https%3A%2F%2Foutlook.office365.com%2Fowa%2F&client_secret=my-client-secret
DEBUG:requests_oauthlib.oauth2_session:Request to fetch token completed with status 200.
DEBUG:requests_oauthlib.oauth2_session:Request headers were {'User-Agent': 'python-requests/2.20.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8', 'Content-Length': '1033', 'Authorization': 'Basic enconded-auth'}
DEBUG:requests_oauthlib.oauth2_session:Request body was grant_type=authorization_code&code=my-code&client_id=my-client-id&redirect_uri=https%3A%2F%2Foutlook.office365.com%2Fowa%2F&client_secret=my-client-secret
DEBUG:requests_oauthlib.oauth2_session:Response headers were {'Cache-Control': 'no-cache, no-store', 'Pragma': 'no-cache', 'Content-Type': 'application/json; charset=utf-8', 'Expires': '-1', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'X-Content-Type-Options': 'nosniff', 'x-ms-request-id': 'request-id', 'P3P': 'xxxxx"', 'Set-Cookie': 'fpc=xxxxxxxx; expires=Sun, 16-Dec-2018 11:01:16 GMT; path=/; secure; HttpOnly, x-ms-gateway-slice=004; path=/; secure; HttpOnly, stsservicecookie=ests; path=/; secure; HttpOnly', 'Date': 'Fri, 16 Nov 2018 11:01:15 GMT', 'Content-Length': '3997'} and content {"token_type":"Bearer","scope":"profile openid email https://graph.microsoft.com/Mail.Read https://graph.microsoft.com/Mail.ReadWrite https://graph.microsoft.com/Mail.Send https://graph.microsoft.com/User.Read","expires_in":3600,"ext_expires_in":3600,"access_token":"my-access-token","refresh_token":"my-refresh-token"}.
DEBUG:requests_oauthlib.oauth2_session:Invoking 0 token response hooks.
DEBUG:requests_oauthlib.oauth2_session:Obtained token {'token_type': 'Bearer', 'scope': ['profile', 'openid', 'email', 'https://graph.microsoft.com/Mail.Read', 'https://graph.microsoft.com/Mail.ReadWrite', 'https://graph.microsoft.com/Mail.Send', 'https://graph.microsoft.com/User.Read'], 'expires_in': 3600, 'ext_expires_in': 3600, 'access_token': 'my-access-token', 'refresh_token': 'my-refresh-token', 'expires_at': 1542369672.7864285}.
Authentication Flow Completed. Oauth Access Token Stored. You can now use the API.
```

Note this two messages:

`DEBUG:requests_oauthlib.oauth2_session:Request to fetch token completed with status 200.`
`Authentication Flow Completed. Oauth Access Token Stored. You can now use the API.`

That means the token was adquired.

It seems you are not passing the url (paste it and hit enter).

The program is awaiting you to paste back the authenticated url. That's why it seems to you that the program stopped responding.

**Comment by zimws** [comment]
so what is the authenticated url? is it the url that it asks me to go to or is the url after I paste into and direct me to my outlook page? I pasted the url of my outlook page after I gave consent and I press return and then the python is not responding.

**Comment by alejcas** [comment]
Thats the url of the outlook owa page that opens after you login and give consent.

If you hit enter and nothing happens I'm afraid I can't help you. That has to be something on your machine... maybe a firewall maybe other thing... I don't know.

What I can tell you is this...

If instead of entering the outlook url you enter something wrong like: 'https://www.google.com' you will see:

`Something go wrong. Please try again.`

If you see nothing then something is wrong...

**Comment by zimws** [comment]
It doesn't work even if I enter google. I am using spyder and the entire thing freezes so I have to force it to terminate.

**Comment by alejcas** [comment]
Try in the command line

**Comment by zimws** [comment]
Ok it managed to proceed in the command line but now it says:
ERROR:O365.connection:Unable to fetch auth token. Error: (mismatching_state) CSRF Warning! State not equal in request and response.
Something go wrong. Please try again.

**Comment by alejcas** [comment]
That means you are pasting a url different than the one generated for you. You have to use the one the programm gives you and then paste the one generated with that url.

Close all browser related pages and start over so you can’t do it wrong by accident

**Comment by zimws** [comment]
Ok, now it says (I removed the client details):
DEBUG:requests_oauthlib.oauth2_session:Encoding client_id "" with client_secret as Basic auth credentials.
DEBUG:requests_oauthlib.oauth2_session:Requesting url https://login.microsoftonline.com/common/oauth2/v2.0/token using method POST.
DEBUG:requests_oauthlib.oauth2_session:Supplying headers {'Accept': 'application/json', 'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8'} and data {'grant_type': 'authorization_code', 'code': '', 'client_id': '', 'redirect_uri': 'https://outlook.office365.com/owa/', 'client_secret': ''}
DEBUG:requests_oauthlib.oauth2_session:Passing through key word arguments {'json': None, 'timeout': None, 'auth': <requests.auth.HTTPBasicAuth object at 0x0000025EC43087B8>, 'verify': True, 'proxies': None}.
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): login.microsoftonline.com:443
DEBUG:urllib3.util.retry:Incremented Retry for (url='/common/oauth2/v2.0/token'): Retry(total=2, connect=3, read=3, redirect=None, status=None)
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=3, read=3, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')])"))': /common/oauth2/v2.0/token
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (2): login.microsoftonline.com:443
DEBUG:urllib3.util.retry:Incremented Retry for (url='/common/oauth2/v2.0/token'): Retry(total=1, connect=3, read=3, redirect=None, status=None)
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=3, read=3, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')])"))': /common/oauth2/v2.0/token
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (3): login.microsoftonline.com:443
DEBUG:urllib3.util.retry:Incremented Retry for (url='/common/oauth2/v2.0/token'): Retry(total=0, connect=3, read=3, redirect=None, status=None)
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=3, read=3, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')])"))': /common/oauth2/v2.0/token
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (4): login.microsoftonline.com:443
ERROR:O365.connection:Unable to fetch auth token. Error: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /common/oauth2/v2.0/token (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')])")))
Something go wrong. Please try again.

**Comment by alejcas** [comment]
As you see it's failing and retrying to connect to [https://login.microsoftonline.com/common/oauth2/v2.0/token](https://login.microsoftonline.com/common/oauth2/v2.0/token) on port 443.

That's has nothing to do with the library.
Try looking for this error on stackoverflow.
