### ISSUE TITLE
get_contacts() -> KeyError: 'id'

### ISSUE THREAD

**Issue by thomas-schulze-entwicklerschmiede** [janscas/py-o365#22]
Hi,

perhaps I am missing something, but using addressbook's get_contacts()
expects a mapping in line 286, at least I think so:

cf. pyo365/address_book.py:283ff:

```python
[..]
if self.root:
    url = self.build_url(self._endpoints.get('root_contacts'))
else:
    url = self.build_url(self._endpoints.get('folder_contacts').format(self.folder_id))
[..]
```

Using the code in original form gives:

> KeyError: 'id'

But changing line 286 into
```python
[..]
if self.root:
    url = self.build_url(self._endpoints.get('root_contacts'))
else:
    url = self.build_url(self._endpoints.get('folder_contacts').format(id=self.folder_id))
[..]
```
appears to work fine. If I didn't miss anything, perhaps You'll add this change
to the code!?

Kind regards

**Comment by alejcas** [comment]
Yes! that's a bug. It's fixed now.
