### ISSUE TITLE
Saving new contacts

### ISSUE THREAD

**Issue by thomas-schulze-entwicklerschmiede** [janscas/py-o365#24]
Hi,

I tried a code-example, but unfortunately that failed: (version 1.01 from PyPi):

```Python
    new_contact = address_book.new_contact()
    new_contact.display_name = "George"
    new_contact.emails.add('george@best.com')
    new_contact.save()
```

gives the error:

> requests.exceptions.HTTPError: 405 Client Error: Method Not Allowed for url: https://graph.microsoft.com/v1.0/me/contacts/...

What am I doing wrong?

I also tried to save a contact into a contact-folder like this:
```Python
        contactbooks = address_book.get_folders()
        new_contact = contactbooks[0].new_contact()
        new_contact.display_name = "George"
        new_contact.emails.add('george@best.com')
        new_contact.save()
```

This gives another internal error:

> .../lib/python3.6/site-packages/O365/address_book.py", line 211, in save
    self._endpoints.get('child_contact').format(self.folder_id))
KeyError: 'id'

Any ideas?

Best regards and many thanks!

**Comment by alejcas** [comment]
Fixed in the O365 repository. Not here.
