### ISSUE TITLE
Publish PIP package?

### ISSUE THREAD

**Issue by vikramgorla** [janscas/py-o365#8]
Hello,
I am looking at using your package in one of opensource automation software, do you have any plans to publish this as pip package/PyPi ?

Thanks

**Comment by alejcas** [comment]
Yes sure. But I'm waiting till 1st November to release it. 
Because then the Outlook Api version 1 is going to be deprecated.

You can check branch "v2" in this project to see the upcoming changes.

Till then you can use the "Clone or Download" option.

**Comment by alejcas** [comment]
I'm back to you just to let you know I merged the v2 branch into master. So now the project is updated to the most up to date version. That means It no longer handles basic authentication. But comes with nre features such as drives managements etc.

Also, **the library is published on pypi.org under the 'pyo365' name**. Check the Readme for further notes.

See ya
