### ISSUE TITLE
filter by receivedDateTime

### ISSUE THREAD

**Issue by jessepink** [janscas/py-o365#9]
It appears the pyo365 generates the following URL when using the receivedDateTime filter:
'https://graph.microsoft.com/v1.0/me/messages?%24top=25&%24filter=receivedDateTime+ge+%272018-10-29T05%3A00%3A00%2B00%3A00%27

This generates a 400 error with the Microsoft Graph API: Failure: Status Code 400

I can manually correct the URL to https://graph.microsoft.com/v1.0/me/messages?%24top=25&%24filter=receivedDateTime+ge+2018-10-29T05%3A00%3A00%2B00%3A00
and it works fine (note that all I did was take out the single quotations/%27 from the datetime stamp.)

I'm not EXACTLY sure where this URL is being generated, or I would attempt to submit a patch myself.  (If I figure it out, I may still do this.)

**Comment by alejcas** [comment]
Can you please paste the function call you use to get the messages?

Are you using the query helper?

**Comment by ppascher** [comment]
I get the same error using the query helper (same for attribute 'created_date_time'):
```query = query.on_attribute('received_date_time').greater(datetime(2018, 10, 29))```
```Filter: receivedDateTime gt '2018-10-28T23:00:00+00:00'
Order: None
Select: None
Client Error: 400 Client Error: Bad Request for url: https://graph.microsoft.com/v1.0/me/mailFolders/Inbox/messages?%24filter=receivedDateTime+gt+%272018-10-28T23%3A00%3A00%2B00%3A00%27&%24top=25
Traceback (most recent call last):
  File "index.py", line 21, in <module>
    messages = inbox.get_messages(limit=25, query=query)
  File "/home/user/.virtualenv/research_rss/lib/python3.5/site-packages/pyo365/mailbox.py", line 138, in get_messages
    response = self.con.get(url, params=params)
  File "/home/user/.virtualenv/research_rss/lib/python3.5/site-packages/pyo365/connection.py", line 476, in get
    return self.oauth_request(url, 'get', params=params, **kwargs)
  File "/home/user/.virtualenv/research_rss/lib/python3.5/site-packages/pyo365/connection.py", line 472, in oauth_request
    return self._internal_request(self.session, url, method, **kwargs)
  File "/home/user/.virtualenv/research_rss/lib/python3.5/site-packages/pyo365/connection.py", line 453, in _internal_request
    raise e
  File "/home/user/.virtualenv/research_rss/lib/python3.5/site-packages/pyo365/connection.py", line 426, in _internal_request
    response.raise_for_status()  # raise 4XX and 5XX error codes.
  File "/home/user/.virtualenv/research_rss/lib/python3.5/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://graph.microsoft.com/v1.0/me/mailFolders/Inbox/messages?%24filter=receivedDateTime+gt+%272018-10-28T23%3A00%3A00%2B00%3A00%27&%24top=25```

**Comment by jessepink** [comment]
yes:
`query = mailbox.new_query()`

`query = query.on_attribute('ReceivedDateTime').greater_equal(datetime(2018, 10, 29, 8, 0))`

`messages = mailbox.get_messages(query=query)`

**Comment by alejcas** [comment]
I have just committed a fix (31f931dd6b76e556a1aef160bf70655fcfa97486). I'll publish a new version on pypi in the following hours.

It now works as expected.

Thanks

**Comment by jessepink** [comment]
That was quick, thanks!

**Comment by alejcas** [comment]
`pip install --upgrade pyo365` should now upgrade to 0.1.3 with some bugs fixed.

See ya
